server:
  port: 9090

spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id : stagiaire-microservice
          uri : lb://STAGIAIRE-SERVICE
          predicates:
            - Path= /api/stagiaire/**
        - id: stage-microservice
          uri : lb://STAGE-SERVICE
          predicates:
            - Path= /api/stage/**
        - id: encadrant-microservice
          uri: lb://ENCADRANT-SERVICE
          predicates:
            - Path= /api/encadrant/**
        - id: departement-microservice
          uri: lb://DEPARTEMENT-SERVICE
          predicates:
            - Path= /api/departement/**

